"""Tests for AppRepository moving an app between revisions, against real repos."""

from __future__ import annotations

import subprocess
from pathlib import Path

from pilot.config import AppConfig
from pilot.core.app.repository import AppRepository
from pilot.internal.git import GitRepo


def _git(path: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(path), *args], check=True, capture_output=True)


def _repo_with_two_commits(path: Path) -> tuple[Path, str]:
    """A repo on `main` with two commits, and the sha of the first."""
    path.mkdir(parents=True)
    subprocess.run(["git", "init", "-q", "-b", "main", str(path)], check=True)
    _git(path, "config", "user.email", "t@t.com")
    _git(path, "config", "user.name", "t")
    (path / "file").write_text("first")
    _git(path, "add", "file")
    _git(path, "commit", "-q", "-m", "first")
    (path / "file").write_text("second")
    _git(path, "commit", "-qam", "second")
    return path, GitRepo(path).head_sha


class _FakeApp:
    def __init__(self, path: Path) -> None:
        self.path = path
        self.config = AppConfig(name="demo", repo="", branch="main")


def _repository(path: Path) -> AppRepository:
    return AppRepository(_FakeApp(path))


def test_checkout_moves_revision_when_a_build_dirtied_the_repo(tmp_path: Path) -> None:
    """Building an app's assets writes generated files back into its own repo, so
    the update after a build meets a dirty tree and git refuses to check out."""
    path, _ = _repo_with_two_commits(tmp_path / "app")
    first = GitRepo(path)._run("rev-parse", "HEAD~1").stdout.strip()
    (path / "file").write_text("regenerated by the asset build")

    _repository(path)._checkout_pinned_ref(first)

    assert GitRepo(path).head_sha == first
    assert (path / "file").read_text() == "first"


def test_checkout_keeps_the_dirty_work_in_the_stash(tmp_path: Path) -> None:
    """The revision moved to may conflict with it, so it is kept rather than
    reapplied - but never dropped, since some of it is the user's own edit."""
    path, _ = _repo_with_two_commits(tmp_path / "app")
    first = GitRepo(path)._run("rev-parse", "HEAD~1").stdout.strip()
    (path / "file").write_text("a local edit worth keeping")

    _repository(path)._checkout_pinned_ref(first)

    assert "stash@{0}" in GitRepo(path)._run("stash", "list").stdout


def test_checkout_of_a_clean_repo_stashes_nothing(tmp_path: Path) -> None:
    path, _ = _repo_with_two_commits(tmp_path / "app")
    first = GitRepo(path)._run("rev-parse", "HEAD~1").stdout.strip()

    _repository(path)._checkout_pinned_ref(first)

    assert GitRepo(path)._run("stash", "list").stdout.strip() == ""
